spring:
  profiles:
    active: dev
  batch:
    job:
      names: ${job.name:none}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/sb_batch?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name:
    username: user2
    password: test1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  logging:
    level:
      com.ll.exam.sb_batch_exam: debug
